### PR TITLE
Add travis.yml script.

### PR DESCRIPTION
**Pull request by chrisdembia**
This is a work-in-progress pull request; I'm still working on it and it's not ready to merge yet.

### CODE REVIEW

**Comment by vmbecerra** [comment]
Thank you. Let me know when it is ready to merge and I will do it.

**Comment by chrisdembia** [comment]
The issue I'm running into is that SuiteSparse is looking to link with openblas using `-lopenblas`, but I think on Ubuntu that openblas is still just named `libblas.so`, so we should be linking using `-lblas.`

**Comment by chrisdembia** [comment]
@vmbecerra the travis.yml script now works! It could use improvement but I suggest we merge it now and we can add improvements over time.

**Comment by vmbecerra** [comment]
Excellent. Thank you Chris.

**Pull request merged**
